version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-logs:/var/log/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db

volumes:
  mariadb-data:
    name: tobaportal-mariadb-data
    driver: local
  mariadb-logs:
    name: tobaportal-mariadb-logs
    driver: local
